pipeline:
  build:
    image: python:3.5-alpine
    commands:
      - python3 manage.py migrate 
      - python3 manage.py loaddata --app users users/fixtures/users.json 
      - python3 manage.py test 
 
